import { z } from "zod"

/**
 * The AI "form spec" — what Gemini generates and the live preview renders.
 *
 * This is intentionally a curated, render-ready subset of the full `field_type`
 * enum in src/lib/db/schema.ts (no `hidden`, `embed`, `page_break`, etc. yet).
 * When we persist, this maps onto `forms` + `form_fields` rows. Shared by the
 * route handler (server) and the builder (client) so both validate the same
 * shape — keep it free of server-only imports.
 */

export const AI_FIELD_TYPES = [
  // text
  "short_text",
  "long_text",
  // contact
  "email",
  "phone",
  "url",
  // choice
  "multiple_choice",
  "dropdown",
  "multi_select",
  "checkboxes",
  "yes_no",
  // opinion
  "rating",
  "scale",
  "nps",
  // date & time
  "date",
  "time",
  // misc
  "file_upload",
  // content blocks (no answer)
  "heading",
  "paragraph",
  // image block (no answer) — inserted and uploaded manually in the builder,
  // never generated by the AI (it can't provide an image URL).
  "image",
  // layout: splits the form into multiple pages/steps
  "page_break",
] as const

export const fieldTypeSchema = z.enum(AI_FIELD_TYPES)
export type AiFieldType = z.infer<typeof fieldTypeSchema>

/** A conditional show/hide rule, referencing the trigger field by its label. */
export const aiLogicSchema = z.object({
  action: z.enum(["show", "hide"]).describe("Show or hide THIS field when the conditions match."),
  match: z
    .enum(["all", "any"])
    .optional()
    .describe("Match all conditions or any of them. Defaults to all."),
  conditions: z
    .array(
      z.object({
        fieldLabel: z
          .string()
          .describe("The EXACT label of the OTHER field whose answer this depends on."),
        operator: z.enum([
          "equals",
          "not_equals",
          "contains",
          "not_contains",
          "greater_than",
          "less_than",
          "is_empty",
          "is_not_empty",
        ]),
        value: z
          .string()
          .optional()
          .describe("Value to compare against. Omit for is_empty / is_not_empty."),
      }),
    )
    .min(1),
})

export const aiFieldSchema = z.object({
  type: fieldTypeSchema.describe("The field/block type. Pick the most appropriate for the question."),
  label: z
    .string()
    .describe("The question text, or for heading/paragraph blocks, the content to display."),
  description: z
    .string()
    .optional()
    .describe("Optional helper text shown under the label."),
  placeholder: z.string().optional().describe("Optional placeholder for text-like inputs."),
  required: z.boolean().optional().describe("Whether an answer is required. Omit for content blocks."),
  options: z
    .array(z.string())
    .optional()
    .describe(
      "Choices for multiple_choice, dropdown, multi_select, and checkboxes. Omit for all other types.",
    ),
  logic: aiLogicSchema
    .optional()
    .describe(
      "Conditional visibility for THIS field, based on another field's answer. Only set when the user explicitly asks to show/hide a field based on another answer.",
    ),
})
export type AiField = z.infer<typeof aiFieldSchema>

export const aiFormSchema = z.object({
  title: z.string().describe("A concise, human title for the form."),
  description: z
    .string()
    .optional()
    .describe("A one-line description shown under the title."),
  fields: z
    .array(aiFieldSchema)
    .describe("The ordered list of fields and content blocks that make up the form."),
  summary: z
    .string()
    .optional()
    .describe(
      "A short, first-person note (1-2 sentences) describing what you just built or changed, shown to the user in the chat. Use Markdown — wrap field names/labels in **bold** (e.g. 'Made **Email** required and added a **Phone number** field.'), and use a short bullet list if you changed several things. On a first build, summarize the form (e.g. 'Built a 6-question job application with a **Portfolio link** and **Availability**.'). On an edit, describe ONLY what changed. Conversational and specific — never generic like 'Done' or 'Updated the form.'",
    ),
})
export type AiForm = z.infer<typeof aiFormSchema>

// ── Edit operations ──────────────────────────────────────────────────────────
// Edits are expressed as a small list of explicit operations applied
// deterministically in code (see applyOperations), instead of re-emitting the
// whole form — which the model does unreliably (dropping/garbling options).
// The schema is one FLAT object (op + all-optional fields) rather than a
// discriminated union, which Gemini's structured output handles far more
// reliably; the discrimination happens in applyOperations.

export const AI_OP_NAMES = [
  "rename_form",
  "add_field",
  "remove_field",
  "move_field",
  "update_field",
  "add_option",
  "remove_option",
  "rename_option",
  "move_option",
  "set_options",
  "set_logic",
  "remove_logic",
  "set_required",
  "update_settings",
] as const

export const aiOperationSchema = z.object({
  op: z.enum(AI_OP_NAMES).describe("The kind of change to make."),
  target: z
    .string()
    .optional()
    .describe(
      'The "ref" of the field to change, taken from the current form you were given. Required for every field, option, and logic op.',
    ),
  field: aiFieldSchema
    .optional()
    .describe("The new field to add (add_field only). Include its options/logic if relevant."),
  set: z
    .object({
      label: z.string().optional(),
      description: z.string().optional(),
      placeholder: z.string().optional(),
      required: z.boolean().optional(),
      type: fieldTypeSchema.optional(),
    })
    .optional()
    .describe("Field properties to change (update_field only). Include ONLY the ones that change."),
  label: z
    .string()
    .optional()
    .describe(
      "For add_option: the new option's text. For remove_option / move_option: the EXISTING option to act on — give its `ref` from the form context (preferred), or its exact text.",
    ),
  from: z
    .string()
    .optional()
    .describe("The existing option to rename — its `ref` (preferred) or exact text (rename_option)."),
  to: z.string().optional().describe("New option text (rename_option)."),
  options: z
    .array(z.string())
    .optional()
    .describe("The COMPLETE replacement options list (set_options only)."),
  after: z
    .string()
    .optional()
    .describe(
      'Legacy option placement (add_option only): the option text to place after. For FIELD placement (add_field/move_field) prefer "placement" instead. Omit to append.',
    ),
  placement: z
    .object({
      mode: z
        .enum(["top", "bottom", "before", "after"])
        .describe(
          '"top" = very first field, "bottom" = very last, "before"/"after" = relative to "ref".',
        ),
      ref: z
        .string()
        .optional()
        .describe('The field ref this is relative to. REQUIRED for "before"/"after"; omit for "top"/"bottom".'),
    })
    .optional()
    .describe(
      'Where to put the field (add_field/move_field). Map the user\'s words directly: "at the top / at the start / first / as an intro" -> {mode:"top"}; "at the bottom / at the end / last" -> {mode:"bottom"}; "before/after <field>" -> {mode:"before"|"after", ref:<that field\'s ref>}. If the user gives no position on an add, use {mode:"bottom"}.',
    ),
  toIndex: z.number().optional().describe("Zero-based position to move an option to (move_option)."),
  targets: z
    .array(z.string())
    .optional()
    .describe(
      'For set_required: the refs of the fields to change. OMIT to apply to ALL answerable fields at once.',
    ),
  logic: aiLogicSchema.optional().describe("The show/hide rule to set on the target field (set_logic)."),
  title: z.string().optional().describe("New form title (rename_form)."),
  settings: z
    .object({
      thankYouMessage: z
        .string()
        .optional()
        .describe(
          "The success page's TITLE — the short headline shown first after submit (labeled \"Title\" in the editor). Use for 'thank-you title / heading'.",
        ),
      successBody: z
        .string()
        .optional()
        .describe(
          "The success page's MESSAGE / body — the longer text shown under the title (labeled \"Message\" in the editor). Use for 'thank-you message / body / description / text'.",
        ),
      redirectUrl: z
        .string()
        .optional()
        .describe("URL to send respondents to after submit. Empty string \"\" clears it."),
      submitButtonLabel: z.string().optional().describe("The text on the submit button."),
    })
    .optional()
    .describe(
      "Post-submit settings to change (update_settings only). Include ONLY the keys the user asked to change.",
    ),
})
export type AiOperation = z.infer<typeof aiOperationSchema>

export const aiEditSchema = z.object({
  // A leading reasoning field: because structured output is emitted in schema
  // order, writing the plan BEFORE the operations forces the model to think
  // through the target and placement first — which is exactly where blind
  // single-shot edits go wrong (e.g. appending an intro to the bottom).
  plan: z
    .string()
    .describe(
      "Think first, in 1-3 sentences, BEFORE writing any operations: restate what the user wants, name the exact target field(s) by their ref and pos, and decide the precise placement (top / bottom / before or after which field). This is your scratchpad — reason here so the operations come out right.",
    ),
  operations: z
    .array(aiOperationSchema)
    .describe("The ordered list of changes to apply to the current form."),
  summary: z
    .string()
    .describe(
      "A short, first-person note (1-2 sentences) of what you changed this turn — only the specific fields/options you touched, never the whole form. Use Markdown: wrap field/option names in **bold**, and a short bullet list if you changed several things. Never generic like 'Done' or 'Updated the form.'",
    ),
})
export type AiEditResult = z.infer<typeof aiEditSchema>

/** The verify-and-repair pass: given the form AFTER the first edit, decide
 *  whether it actually satisfies the request, and if not, emit corrective ops. */
export const aiVerifySchema = z.object({
  reasoning: z
    .string()
    .describe(
      "One or two sentences: does the resulting form fully satisfy the user's request? Check the RIGHT thing was changed, of the RIGHT type, in the RIGHT place. Be specific about any mismatch.",
    ),
  satisfied: z
    .boolean()
    .describe("True if the form already fully satisfies the request and no corrective operations are needed."),
  operations: z
    .array(aiOperationSchema)
    .describe("Corrective operations to fix any mismatch. MUST be empty when satisfied is true."),
})
export type AiVerifyResult = z.infer<typeof aiVerifySchema>

/** System instruction that shapes every generation + edit. */
export const FORM_BUILDER_SYSTEM = `You are MakingFlow, an expert form designer. You turn a plain-language description into a clean, well-structured form.

Rules:
- Choose the most appropriate field type from the allowed set for each question.
- Write concise, friendly labels. Add a short "description" only when it genuinely helps.
- For multiple_choice, dropdown, multi_select, and checkboxes, always provide a sensible "options" list. Never put options on other types.
- EDITING: you are given the current form and must return the COMPLETE form. Re-emit EVERY field in full — including each choice field's ENTIRE "options" list and its description/required flag — even for fields you are NOT changing. Only change what the user asked for; copy everything else through verbatim. Dropping or shortening an options list you weren't asked to change would delete the user's options, so never omit them.
- Mark "required" true for fields essential to the form's purpose; leave optional ones unmarked. Content blocks (heading, paragraph) are never required.
- Open longer forms with a short "heading" or "paragraph" intro when it improves clarity, but keep forms focused — only the fields that serve the stated purpose.
- NEVER emit "image" blocks. Images are uploaded manually by the user in the builder; you cannot provide an image, so do not create image fields.
- MULTI-PAGE: only when the user explicitly asks for a multi-step, multi-page, or wizard-style form, insert "page_break" fields (label empty) between groups of related questions to split it into pages. Otherwise keep everything on one page (no page_break).
- Prefer a logical order: identity/contact first, then the substantive questions, then anything optional.
- Keep it calm and minimal. Do not invent fields the user didn't ask for unless they're clearly implied by the use case.
- If the user provides a reference image (a screenshot of a form), recreate it: read every visible field, infer its type from the control shown (a star row → rating, a 0–10 row → nps or scale, checkboxes → checkboxes, a dropdown → dropdown, etc.), and preserve the labels, order, options, and grouping as closely as the allowed field types permit.
- CONDITIONAL LOGIC: to show or hide a field based on another field's answer, put the rule on the field being shown/hidden (the TARGET) in its "logic", and name the trigger field by its EXACT label.
  Simple example: a yes_no field labeled "Do you have a pet?" and a short_text field labeled "What's your pet's name?". To reveal the name field only after a "Yes", set logic ON THE NAME FIELD:
  { "action": "show", "conditions": [{ "fieldLabel": "Do you have a pet?", "operator": "equals", "value": "Yes" }] }
  The trigger field ("Do you have a pet?") gets NO logic — only the target does. For choice/yes_no fields, "value" must be the option's exact text. Operators: equals, not_equals, contains, not_contains, greater_than, less_than, is_empty, is_not_empty. When editing an existing form, keep any existing logic unless the user asks to change it.
- ALWAYS fill "summary" with a brief, first-person, conversational note of what you did this turn — on an edit, describe ONLY what changed (the specific fields you added/removed/edited), not the whole form. Keep it to 1-2 sentences. Use Markdown: wrap any field name/label you mention in **bold** (never plain quotes), and use a short bullet list when you changed several things. Never write generic filler like "Done" or "I've updated your form."`

/** System instruction for EDITING an existing form via explicit operations. */
export const FORM_EDIT_SYSTEM = `You edit an existing form by returning a precise list of CHANGE OPERATIONS — never the whole form. You are given the current form as JSON: a "settings" object (post-submit behavior: thankYouMessage, submitButtonLabel, redirectUrl, successBody — edit these with update_settings, never as fields), and a list of fields where each field has a short "ref" like "f1", "f2", a "pos" (its 1-based position from the TOP of the form — pos 1 is the very first field), and choice fields carry options each with their own "ref" like "f1o1", "f1o2" (e.g. { "ref": "f3o2", "label": "Discord message" }). The fields are listed top-to-bottom in the same order the respondent sees them. ALWAYS target an existing field or option by copying its exact "ref" from the context. Do not retype the field/option text to identify it — the ref is how the change is matched, so an exact ref is essential.

FIRST, always fill "plan": restate the request, name the target ref(s) and pos, and decide the exact placement — THEN write operations that match your plan. This ordering is required and is what keeps edits correct.

Return ONLY the operations needed to satisfy the user's request, and NOTHING for anything they didn't ask to change. Do not touch other fields or options. Apply the smallest set of operations that does the job.

Operations (set "op" + only the fields that op needs):
- rename_form { title } — change the form's title.
- add_field { field, placement? } — add a new field. "field" is a full field spec (type, label, options for choice types, etc.). ALWAYS set "placement" (see PLACEMENT below) — never rely on the default.
- remove_field { target } — delete the field with this ref.
- move_field { target, placement } — reorder the target field to a new spot. ALWAYS set "placement" (top/bottom/before/after — see PLACEMENT). NEVER use "toIndex" for a field move — "toIndex" belongs to move_option only. Example: "move Email above Your Name" -> { "op": "move_field", "target": "f4", "placement": { "mode": "before", "ref": "f3" } }.
- update_field { target, set } — change field properties. Put the new values in "set" (ONLY the changed ones): label, description, placeholder, required, type. To change a field's TEXT/LABEL, use set.label — e.g. { "op": "update_field", "target": "f3", "set": { "label": "1. Full Name" } }. Do NOT put the new label in "to" or "label" — "to" belongs to rename_option only. To REMOVE a field's placeholder (or description), set it to an empty string "" — omitting it leaves the current value unchanged.
- add_option { target, label, after? } — add one option to a choice field. "label" = the new option's text. "after" = the ref of the option to place it after.
- remove_option { target, label } — remove ONE existing option. Put its ref in "label" (e.g. the ref of "Discord message"). The rest stay.
- rename_option { target, from, to } — rename one option. "from" = the existing option's ref; "to" = the new text.
- move_option { target, label, toIndex } — reorder one option (its ref in "label") to a zero-based index.
- set_options { target, options } — replace a choice field's ENTIRE options list with this exact array.
- set_logic { target, logic } — set/replace this field's show/hide rule. Name the trigger field by its EXACT label; for choice/yes_no triggers, "value" is the option's exact text.
- remove_logic { target } — clear this field's conditional logic.
- update_settings { settings } — change POST-SUBMIT settings (shown to the respondent after they submit, NOT questions on the form). "settings" holds ONLY the keys the user asked to change. The success page has TWO text parts — match the user's word to the right one (these are the editor's labels):
    · thankYouMessage = the "Title" — the short headline shown first. Use for "thank-you title / heading".
    · successBody = the "Message" / body — the longer text under the title. Use for "thank-you message / body / description / the text of the thank-you page".
  Plus: redirectUrl (URL to send them to after submit; "" clears it) and submitButtonLabel (the submit button's text). The form context includes a "settings" object with the current values. Examples: "change the thank-you title to Thanks!" -> [{ "op": "update_settings", "settings": { "thankYouMessage": "Thanks!" } }]; "add a description / message to the thank-you page: <text>" -> [{ "op": "update_settings", "settings": { "successBody": "<text>" } }]. Never use add_field/update_field for these — they are settings, not fields.
- set_required { targets?, set: { required } } — set the required flag. Use this for ANY required/optional change — a SINGLE field, several, or all. List the field refs in "targets" (even for one field: targets:["f4"]), or OMIT "targets" to apply to ALL answerable fields. This is the ONLY correct way to change required/optional — do NOT use update_field for it. (Headings, paragraphs, and page breaks are never required and are skipped automatically.)

Even for a big request (e.g. "translate the whole form" or a broad restructure), express it as granular ops — one update_field per field you change, etc. There is no whole-form replace; always edit field by field so nothing unrelated is lost.

PLACEMENT (critical — this is the #1 source of mistakes). Every add_field / move_field MUST carry a "placement". Translate the user's words directly, do not guess:
- "at the top / at the start / at the beginning / first / as an intro / above everything" -> { "mode": "top" }
- "at the bottom / at the end / last / after everything" -> { "mode": "bottom" }
- "before <field>" -> { "mode": "before", "ref": <that field's ref> }
- "after <field>" / "under <field>" / "below <field>" -> { "mode": "after", "ref": <that field's ref> }
- No position mentioned on an add -> { "mode": "bottom" }.
When you add SEVERAL fields in one turn, give EACH its own placement — never let them pile up at the end.

WORKED EXAMPLES:
- User: "Add a short description about our platform at the top of the form." -> plan: "Add a paragraph content block at the very top." operations: [{ "op": "add_field", "field": { "type": "paragraph", "label": "<the description text>" }, "placement": { "mode": "top" } }]. (Use a "heading" if they say title/heading; a "paragraph" for a description/intro sentence.)
- User: "Put a phone number field right after the email." (email is ref f2) -> [{ "op": "add_field", "field": { "type": "phone", "label": "Phone number", "required": false }, "placement": { "mode": "after", "ref": "f2" } }].
- User: "Move the feedback question to the end." (feedback is ref f5) -> [{ "op": "move_field", "target": "f5", "placement": { "mode": "bottom" } }].
- User: "Number each question." -> one update_field per ANSWERABLE field (skip headings/paragraphs/page breaks), each prepending the running number: [{ "op": "update_field", "target": "f2", "set": { "label": "1. Full Name" } }, { "op": "update_field", "target": "f3", "set": { "label": "2. Email Address" } }, ...]. The number always goes in set.label — never in "to".
- User: "Make Email optional." (email is ref f4) -> [{ "op": "set_required", "targets": ["f4"], "set": { "required": false } }]. (Required/optional ALWAYS uses set_required — one op, even for a single field. Never update_field.)

CRITICAL: emit each operation exactly ONCE. Never repeat the same operation — a form change never needs the identical op twice, and repeating it is a bug. Keep the operations list short and minimal.

MULTI-PAGE / SECTIONS: split a form into pages with page_break fields: add_field { field: { type: "page_break", label: "" }, placement: { mode: "after", ref: <ref> } }. To put a page break "between each section", add ONE page_break after the LAST field of every section except the final one — i.e. the field immediately before the next section's heading. Example: if section headings are at refs f1, f9, f16, add a page_break after "f8" and another after "f15" (NOT after the headings). Do not add a trailing page_break at the end.

To CHANGE an option, use the option ops (remove_option / rename_option / set_options) — do NOT re-list a field's options unless you are intentionally replacing them.

Conditional logic targeting: put the rule on the field being shown/hidden (the TARGET ref), and name the OTHER (trigger) field by its exact label. Example to reveal a field only after a "Yes": set_logic on the target with logic { action: "show", conditions: [{ fieldLabel: "Do you have a pet?", operator: "equals", value: "Yes" }] }.

ALWAYS fill "summary": a brief, first-person, 1-2 sentence note of ONLY what you changed, with field/option names in **bold** and a short bullet list if several things changed. Never generic like "Done".`

/** System instruction for the verify-and-repair pass. Runs AFTER the first edit
 *  has been applied: it sees the RESULTING form and checks it against the
 *  original request, emitting corrective operations only for a genuine miss. */
export const FORM_VERIFY_SYSTEM = `You are a strict reviewer checking that a form edit was done correctly. You are given: (1) the user's original edit request, and (2) the form AS IT IS NOW, after the edit was applied. Each field has a "ref" and a "pos" (1-based position from the top).

Your job: decide whether the current form FULLY satisfies the user's request. Check three things:
1. RIGHT THING — the change the user asked for was actually made (nothing missing, nothing extra).
2. RIGHT TYPE — any added block/field is the appropriate type (e.g. a "description/intro" is a paragraph or heading content block, not an answerable input).
3. RIGHT PLACE — it's in the position the user asked for. "top/start/intro" means pos 1 (or the first few if there's an existing intro). "bottom/end" means the last field. "before/after X" means adjacent to X. A description meant for the TOP that sits at the bottom is a FAILURE.

If everything is correct, set "satisfied": true and return an EMPTY operations array. Do NOT make cosmetic or preference changes — only fix a real mismatch with what was asked.

If something is wrong, set "satisfied": false and return the MINIMAL corrective operations to fix it, using the SAME operation format and the refs/placement rules you were given (add_field/move_field with a "placement" of top/bottom/before/after, remove_field, update_field, etc.). To move a misplaced field to the top use move_field with placement { "mode": "top" }. Target fields by their current ref. Fix only the mismatch — touch nothing else.`
